// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/app/AppButton.vue')['default']
    CartSidebar: typeof import('./components/aside/CartSidebar.vue')['default']
    HelloWorld: typeof import('./components/vue/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Navbar: typeof import('./components/Navbar/index.vue')['default']
    NavButton: typeof import('./components/Navbar/NavButton.vue')['default']
    NavDrop: typeof import('./components/Navbar/NavDrop.vue')['default']
    ProfileButton: typeof import('./components/Navbar/ProfileButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/aside/Sidebar.vue')['default']
    TheWelcome: typeof import('./components/vue/TheWelcome.vue')['default']
    UserProfile: typeof import('./components/Navbar/UserProfile.vue')['default']
    WelcomeItem: typeof import('./components/vue/WelcomeItem.vue')['default']
  }
}
